package CollegeAdmissions;

import java.util.ArrayList;

//The class for applicants 
public class Applicant {
	private String Fname;
	private String Lname;
	private int age;
	private Grades grades; 
	private ArrayList<TestScore> testScores;
	private CriminalHistory history;
	private Residence residence;
	private String rejected; 
	
// Constructor 
public Applicant (String Fname,
		               String Lname,
		               int age, 
		               Grades grades, 
		               ArrayList<TestScore> testScores,
		               CriminalHistory history,
		               Residence residence,
		               String rejected)
{
	this.Fname = Fname;
	this.Lname = Lname;
    this.age = age;
	this.grades = grades;
    this.testScores = testScores;
    this.history = history; 
    this.residence = residence;
    this.rejected = rejected;
}

//partial constructor 
public Applicant (String Fname,
        String Lname,
        int age, 
        Grades grades, 
        ArrayList<TestScore> testScores,
        CriminalHistory history,
        Residence residence)
{
this.Fname = Fname;
this.Lname = Lname;
this.age = age;
this.grades = grades;
this.testScores = testScores;
this.history = history; 
this.residence = residence;
rejected = "";
}




public String getRejected() {
	return rejected;
}


public void setRejected(String rejected) {
	this.rejected = rejected;
}


// Autogenerated Accessors/Mutators for OOD compliance 
public int getAge() {
	return age;
}

public void setAge(int age) {
	this.age = age;
}

public Grades getGrades() {
	return grades;
}

public void setGrades(Grades grades) {
	this.grades = grades;
}

public ArrayList<TestScore> getTestScores() {
	return testScores;
}

public void setTestScores(ArrayList<TestScore> testScores) {
	this.testScores = testScores;
}

public CriminalHistory getHistory() {
	return history;
}

public void setHistory(CriminalHistory history) {
	this.history = history;
}

public Residence getResidence() {
	return residence;
}

public void setResidence(Residence residence) {
	this.residence = residence;
}



public String getFname() {
	return Fname;
}



public void setFname(String fname) {
	Fname = fname;
}



public String getLname() {
	return Lname;
}



public void setLname(String lname) {
	Lname = lname;
}




	
	
	
	

}
