package CollegeAdmissions;

import java.util.ArrayList;

//The class for applicants 
public class Applicant {
	private String Fname;
	private String Lname;
	private int age;
	private Grades grades; 
	private ArrayList<TestScore> testScores;
	private CriminalHistory history;
	private String residence;
	
// Constructor 
public Applicant (String Fname,
		               String Lname,
		               int age, 
		               Grades grades, 
		               ArrayList<TestScore> testScores,
		               CriminalHistory history,
		               String residence)
{
	this.Fname = Fname;
	this.Lname = Lname;
    this.age = age;
	this.grades = grades;
    this.testScores = testScores;
    this.history = history; 
    this.residence = residence;
}


// Autogenerated Accessors/Mutators for OOD compliance 
public int getAge() {
	return age;
}

public void setAge(int age) {
	this.age = age;
}

public Grades getGrades() {
	return grades;
}

public void setGrades(Grades grades) {
	this.grades = grades;
}

public ArrayList<TestScore> getTestScores() {
	return testScores;
}

public void setTestScores(ArrayList<TestScore> testScores) {
	this.testScores = testScores;
}

public CriminalHistory getHistory() {
	return history;
}

public void setHistory(CriminalHistory history) {
	this.history = history;
}

public String getResidence() {
	return residence;
}

public void setResidence(String residence) {
	this.residence = residence;
}



public String getFname() {
	return Fname;
}



public void setFname(String fname) {
	Fname = fname;
}



public String getLname() {
	return Lname;
}



public void setLname(String lname) {
	Lname = lname;
}




	
	
	
	

}
